/*
-- Query: select * from mu.services
-- Date: 2020-11-14 18:42
*/
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (49,'(+380)-22-416-2377','EmmelineSims8gmail.com',1,'#201219',6563,'Emmeline',40);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (2,'Print without correction','MaryFox5gmail.com',845,'#200078',31,'4/8/2007',23);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (3,'Print without correction','Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.',551,'#20201211',37,'3/19/2014',35);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (83,'Print with light correction','JaneGriffin9gmail.com',0,'#2005625',6096,'1/19/2004',49);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (5,'Special order','Nullam dictum felis eu pede mollis pretium. Integer tincidunt.',477,'#2014619',10,'5/28/2016',38);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (6,'Print with light correction','Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.',568,'#2013117',29,'8/16/2017',42);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (34,'Print without correction','FayAndrews9gmail.com',1,'#200273',3894,'2/2/2005',31);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (8,'Print and cuting ','Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum.',583,'#2012219',7,'7/10/2016',14);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (9,'Print without correction','Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.',498,'#200988',11,'6/15/2009',23);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (11,'Special order','CatherinePhelps2gmail.com',571,'#200938',4351,'5/15/2003',6);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (12,'Print and use special paper','Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui.',446,'#2014910',21,'2/7/2004',31);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (13,'Print without correction','Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;',688,'#202089',39,'7/12/2004',4);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (69,'(+380)-65-964-7635','RebeccaFarmer7gmail.com',1,'#2009109',1068,'7/21/2004',32);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (15,'Print with light correction','Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero.',559,'#20091024',17,'11/26/2006',19);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (16,'Print without correction','Cras id dui. Aenean ut eros et nisl sagittis vestibulum.',659,'#20161012',12,'10/11/2003',10);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (17,'Print and cuting ','RosaWelch5gmail.com',1,'#2012127',8124,'8/18/2017',29);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (18,'Print without correction','Donec mollis hendrerit risus. Phasellus nec sem in justo pellentesque facilisis.',398,'#2016523',17,'4/28/2009',15);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (19,'Print with light correction','Etiam imperdiet imperdiet orci. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi.',938,'#2020120',36,'9/17/2019',41);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (58,'Print and use special paper','TraceyHoward1gmail.com',1,'#2007814',3366,'12/7/2011',37);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (21,'Print and cuting ','Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu. Phasellus accumsan cursus velit.',927,'#2004910',1,'7/15/2005',30);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (22,'Print without correction','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue',361,'#2019312',41,'10/17/2005',36);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (23,'Print card with laminate','AllisonSmall4gmail.com',677,'#2011118',5455,'1/2/2020',6);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (24,'Print with light correction','Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc. Vestibulum fringilla pede sit amet augue.',423,'#2001923',28,'3/6/2011',6);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (25,'Print and use special paper','In turpis. Pellentesque posuere. Praesent turpis. Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus.',446,'#2019108',48,'8/8/2010',38);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (27,'Print and cuting ','LilyMay5gmail.com',563,'#2009114',32,'7/18/2009',9);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (28,'Print card with laminate','Maecenas vestibulum mollis diam. Pellentesque ut neque. Pellentesque habitant morbi tristique senectus et netus',999,'#2020915',6,'8/25/2011',7);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (29,'Print book with laminate','et malesuada fames ac turpis egestas. In dui magna, posuere eget, vestibulum et, tempor auctor, justo. In ac felis quis tortor malesuada pretium. Pellentesque auctor neque nec urna. Proin sapien ipsum, porta a, auctor quis, euismod ut, mi.',921,'#201597',41,'10/2/2020',21);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (30,'Special order','OliviaMerritt5gmail.com',530,'#2020627',8833,'8/3/2008',15);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (31,'Print and use special paper','Ut non enim eleifend felis pretium feugiat. Vivamus quis mi. Phasellus a est. Phasellus magna',910,'#2001113',48,'2/5/2017',20);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (33,'Print without correction','EmilyHardy9gmail.com',1,'#2001621',7259,'12/15/2002',10);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (37,'Print book with laminate','BettyGreene1gmail.com',369,'#2016922',1543,'6/2/2012',33);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (38,'Print without correction','Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna. Vestibulum ullamcorper mauris at ligula.',908,'#20001113',32,'4/22/2004',44);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (86,'Special order','SarahParks3gmail.com',0,'#2017114',735,'1/16/2014',19);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (40,'Print with light correction','Ut tincidunt tincidunt erat. Etiam feugiat lorem non metus. Vestibulum dapibus nunc ac augue. Curabitur vestibulum aliquam leo.',788,'#20011214',2,'8/1/2011',41);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (41,'Print without correction','Praesent egestas neque eu enim. In hac habitasse platea dictumst. Fusce a quam. Etiam ut purus mattis mauris sodales aliquam. Curabitur nisi. Quisque malesuada placerat nisl. Nam ipsum risus, rutrum vitae, vestibulum eu, molestie vel, lacus.',479,'#2013418',19,'3/19/2007',40);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (72,'(+380)-39-759-6297','EmmaGarrison6gmail.com',1,'#2018315',1431,'9/10/2007',15);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (43,'Print without correction','Proin faucibus arcu quis ante. In consectetuer turpis ut velit. Nulla sit amet est. Praesent metus tellus, elementum eu, semper a, adipiscing nec, purus.',906,'#2001621',34,'2/27/2011',16);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (44,'Print without correction','Nulla neque dolor, sagittis eget, iaculis quis, molestie non, velit. Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula. Fusce pharetra convallis urna. Quisque ut nisi.',810,'#2010726',36,'12/9/2004',16);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (54,'Print with light correction','GraceHopkins7gmail.com',0,'#200917',4067,'5/5/2012',7);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (46,'Print card with laminate','Curabitur suscipit suscipit tellus. Praesent vestibulum dapibus nibh. Etiam iaculis nunc ac metus. Ut id nisl quis enim dignissim sagittis.  Etiam sollicitudin,ipsum eu pulvinar rutrum,tellus ipsum laoreet sapien,quis venenatis ante odio sit amet eros. Proin magna. Duis vel nibh at velit scelerisque suscipit. Curabitur turpis. Vestibulum suscipit nulla quis orci. Fusce ac felis sit amet ligula pharetra condimentum.',693,'#2019627',46,'5/20/2000',27);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (47,'Print and use special paper','Maecenas egestas arcu quis ligula mattis placerat. Duis lobortis massa imperdiet quam. Suspendisse potenti. Pellentesque commodo eros a enim. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Sed libero.',922,'#2015524',26,'11/13/2012',24);
INSERT INTO mu.services (`idSerivces`,`name_service`,`Description`,`Price`,`code_service`,`fk_service_paper`,`serviceDATE`,`fk_service_fonts`) VALUES (50,'Print without correction','ChloeWatts8gmail.com',466,'#2017420',46,'9/16/2017',41);
