/*
-- Query: select * from mu.paper
-- Date: 2020-11-14 18:41
*/
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (1,'self-adhesive','A0',841,1189,2,23,5.3,'0','7461.6','CarolSparks2gmail.com','2/5/2007');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (2,'usual','A1',594,841,1,7,4.4,'1','4877.3','KatherineLester4gmail.com','5/4/2002');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (3,'self-adhesive','A2',420,594,2,2,4.8,'yellow','4280.8','DorothyParrish3gmail.com','5/21/2015');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (4,'self-adhesive','A3',297,420,1,7,5.9,'black','none','In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.','12/24/2004');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (5,'self-adhesive','A4',210,297,1,2,5.8,'black','matt','Nullam dictum felis eu pede mollis pretium. Integer tincidunt.','8/21/2001');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (6,'self-adhesive','A5',148,210,2,7,2.9,'black','none','Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.','7/16/2012');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (8,'self-adhesive','A7',74,105,4,3,2.8,'black','none','Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum.','8/14/2016');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (12,'self-adhesive','B0',1000,1414,4,2,1.7,'yellow','rough','Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui.','8/10/2008');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (13,'usual','B1',707,1000,4,6,1.9,'black','none','Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;','6/5/2009');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (14,'self-adhesive','B2',500,707,2,7,3.2,'black','matt','In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris.','10/15/2012');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (15,'usual','B3',353,500,4,2,3.6,'dark gray','none','Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero.','4/27/2000');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (16,'self-adhesive','B4',250,353,3,4,2.4,'black','none','Cras id dui. Aenean ut eros et nisl sagittis vestibulum.','10/1/2009');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (17,'self-adhesive','B5',176,250,1,1,4.3,'black','none','Nullam nulla eros, ultricies sit amet, nonummy id, imperdiet feugiat, pede. Sed lectus.','2/24/2012');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (28,'self-adhesive','C5',162,229,4,1,5.6,'black','none','Maecenas vestibulum mollis diam. Pellentesque ut neque. Pellentesque habitant morbi tristique senectus et netus','9/23/2020');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (29,'self-adhesive','C6',114,162,3,1,3.7,'black','smooth','et malesuada fames ac turpis egestas. In dui magna, posuere eget, vestibulum et, tempor auctor, justo. In ac felis quis tortor malesuada pretium. Pellentesque auctor neque nec urna. Proin sapien ipsum, porta a, auctor quis, euismod ut, mi.','10/10/2003');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (30,'self-adhesive','C7',81,114,2,2,3.7,'gray','matt','Aenean viverra rhoncus pede. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.','11/22/2018');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (31,'self-adhesive','C8',57,81,2,4,5.1,'black','none','Ut non enim eleifend felis pretium feugiat. Vivamus quis mi. Phasellus a est. Phasellus magna','1/23/2010');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (32,'self-adhesive','C9',40,57,2,5,2.6,'black','none','In hac habitasse platea dictumst. Curabitur at lacus ac velit ornare lobortis.','8/11/2014');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (33,'self-adhesive','C10',28,40,3,3,2.8,'black','none','Curabitur a felis in nunc fringilla tristique. Morbi mattis ullamcorper velit. Phasellus gravida semper nisi. Nullam vel sem. Pellentesque libero tortor, tincidunt et, tincidunt eget, semper nec, quam. Sed hendrerit.','9/12/2000');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (36,'newsprint','A2',420,594,4,2,1.5,'black','smooth','AbigailBrooks3gmail.com','3/20/2011');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (37,'newsprint','A3',297,420,2,4,1.2,'yellow','none','Morbi nec metus. Phasellus blandit leo ut odio. Maecenas ullamcorper, dui et placerat feugiat, eros pede varius nisi, condimentum viverra felis nunc et lorem. Sed magna purus, fermentum eu, tincidunt eu, varius ut, felis. In auctor lobortis lacus.','3/8/2015');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (38,'newsprint','A4',210,297,1,5,1.2,'dark gray','matt','Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna. Vestibulum ullamcorper mauris at ligula.','4/18/2006');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (41,'newsprint','A7',74,105,3,6,4.5,'black','none','Praesent egestas neque eu enim. In hac habitasse platea dictumst. Fusce a quam. Etiam ut purus mattis mauris sodales aliquam. Curabitur nisi. Quisque malesuada placerat nisl. Nam ipsum risus, rutrum vitae, vestibulum eu, molestie vel, lacus.','10/13/2009');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (42,'newsprint','A8',52,74,1,6,5.5,'dark gray','matt','Sed augue ipsum, egestas nec, vestibulum et, malesuada adipiscing, dui. Vestibulum facilisis, purus nec pulvinar iaculis, ligula mi congue nunc, vitae euismod ligula urna in dolor. Mauris sollicitudin fermentum libero.','12/27/2001');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (43,'newsprint','A9',37,52,1,6,5.5,'yellow','smooth','Proin faucibus arcu quis ante. In consectetuer turpis ut velit. Nulla sit amet est. Praesent metus tellus, elementum eu, semper a, adipiscing nec, purus.','3/28/2015');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (44,'newsprint','A10',26,37,2,3,1.4,'black','none','Nulla neque dolor, sagittis eget, iaculis quis, molestie non, velit. Mauris turpis nunc, blandit et, volutpat molestie, porta ut, ligula. Fusce pharetra convallis urna. Quisque ut nisi.','11/23/2008');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (46,'usual','A4',210,297,2,6,1.1,'dark gray','none','Curabitur suscipit suscipit tellus. Praesent vestibulum dapibus nibh. Etiam iaculis nunc ac metus. Ut id nisl quis enim dignissim sagittis.  Etiam sollicitudin,ipsum eu pulvinar rutrum,tellus ipsum laoreet sapien,quis venenatis ante odio sit amet eros. Proin magna. Duis vel nibh at velit scelerisque suscipit. Curabitur turpis. Vestibulum suscipit nulla quis orci. Fusce ac felis sit amet ligula pharetra condimentum.','8/14/2000');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (47,'usual','A5',148,210,3,4,4.7,'black','smooth','Maecenas egestas arcu quis ligula mattis placerat. Duis lobortis massa imperdiet quam. Suspendisse potenti. Pellentesque commodo eros a enim. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Sed libero.','4/2/2013');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (48,'usual','A6',105,148,3,5,5.3,'black','none','Aliquam erat volutpat. Etiam vitae tortor. Morbi vestibulum volutpat enim. Aliquam eu nunc.','2/7/2000');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (49,'usual','A7',74,105,1,6,2.9,'dark gray','rough','Etiam ut purus mattis mauris sodales aliquam. Curabitur nisi. Quisque malesuada placerat nisl. Nam ipsum risus, rutrum vitae, vestibulum eu, molestie vel, lacus. Sed augue ipsum, egestas nec, vestibulum et, malesuada adipiscing, dui.','1/19/2005');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (50,'usual','A8',52,74,3,1,2.9,'black','none','Sed mollis, eros et ultrices tempus, mauris ipsum aliquam libero,','4/22/2006');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (18,'self-adhesive','B6',125,176,4,2,2.5,'gray','7769.6','VirginiaBailey5gmail.com','10/22/2014');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (19,'self-adhesive','B7',88,125,1,7,4.3,'black','matt','NancyBooth5gmail.com','11/17/2013');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (20,'usual','B8',62,88,4,2,3.6,'dark gray','none','Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Maecenas malesuada.','4/6/2013');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (21,'self-adhesive','B9',44,62,1,3,3.5,'black','smooth','Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu. Phasellus accumsan cursus velit.','5/24/2007');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (22,'self-adhesive','B10',31,44,4,2,2.1,'black','none','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue','10/10/2007');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (23,'self-adhesive','C0',917,1297,1,3,3.5,'dark gray','matt','elit erat euismod orci, ac placerat dolor lectus quis orci. Phasellus consectetuer vestibulum elit.','5/26/2005');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (40,'newsprint','A6',105,148,1,7,1.8,'black','rough','Ut tincidunt tincidunt erat. Etiam feugiat lorem non metus. Vestibulum dapibus nunc ac augue. Curabitur vestibulum aliquam leo.','2/27/2020');
INSERT INTO mu.paper (`idPaper`,`name_paper`,`iso_format`,`height`,`width`,`fk_paper_to_bright`,`fk_paper_to_density`,`thickness`,`color`,`covering`,`description`,`paperDATE`) VALUES (45,'usual','A3',297,420,1,39,4.3,'1','7223.9','MadisonRose5gmail.com','9/8/2001');
