/*
-- Query: SELECT * FROM inno.paper_density
-- Date: 2020-11-20 01:25
*/
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (1,1.5,'On insensible possession');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (2,1.2,'oh particular attachment');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (3,1.2,'The books arose');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (4,2.9,'but miles happy she');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (5,1.7,'It building contempt');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (6,1.6,'Suppose cottage between');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (7,2.9,'or interest children ');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (8,2.6,'children  unlocked no');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (9,2.6,'Minuter him own');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (10,1.6,' Nullam quis ante');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (11,1.1,'Offending she contained');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (12,1.7,'Fusce vulputate eleifend sapien');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (13,2.2,'Delicate marianne absolute');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (14,2.7,'In ac dui quis');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (15,1.1,'Praesent adipiscing');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (16,1.3,'Cras id dui. Aenean ut eros et');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (17,2.1,'Agreement far boy');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (18,2.3,'otherwise rapturous incommode');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (19,1.6,'He difficult contented');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (20,1.3,'we determine ourselves');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (21,2.2,'men dashwood landlord');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (22,1.5,'me am earnestly');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (23,2.8,'Hour no find it park');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (24,1.2,'Eat welcomed any');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (25,1.5,'husbands moderate');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (26,1.7,'Led was misery played');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (27,1.5,'waited almost cousin living');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (28,2.1,'Of intention contained');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (29,2.3,'is by middleton am');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (30,2.6,'Principles fat stimulated');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (31,1.2,'uncommonly considered');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (32,1.3,'set especially prosperous');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (33,1.9,'Sons at park');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (34,2.3,'mr meet as fact like');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (35,1.6,'Unpacked now declared');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (36,1.9,'put you confined');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (37,1.4,'daughter improved');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (38,2.5,'Celebrated imprudence');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (39,1.8,'few interested');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (40,2.1,'especially reasonable');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (41,1.3,'Wonder bed elinor');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (42,1.1,'It want gave west ');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (43,2.2,'into high no in');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (44,1.1,'Bringing so sociable ');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (45,2.1,'felicity supplied mr');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (46,2.5,'September suspicion');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (47,2.5,'far him two acuteness perfectly.');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (48,2.9,'Covered as an examine');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (49,2.2,'Ye astonished friendship');
INSERT INTO inno.paper_density (`id`,`lvl`,`desc`) VALUES (50,2.6,'remarkably no');
