/*
-- Query: SELECT * FROM inno.paper_brightness
-- Date: 2020-11-20 01:24
*/
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (1,1.4,'On insensible possession');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (2,3.3,'oh particular attachment');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (3,2.9,'The books arose');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (4,1.2,'but miles happy she');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (5,2.9,'It building contempt');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (6,3.3,'Suppose cottage between');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (7,5.6,'or interest children ');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (8,3.5,'children  unlocked no');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (9,4.5,'Minuter him own');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (10,1.5,' Nullam quis ante');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (11,3.4,'Offending she contained');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (12,5.9,'Fusce vulputate eleifend sapien');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (13,2.3,'Delicate marianne absolute');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (14,2.8,'In ac dui quis');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (15,3.9,'Praesent adipiscing');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (16,1.2,'Cras id dui. Aenean ut eros et');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (17,4.6,'Agreement far boy');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (18,4.9,'otherwise rapturous incommode');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (19,3.1,'He difficult contented');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (20,1.5,'we determine ourselves');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (21,1.7,'men dashwood landlord');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (22,4.7,'me am earnestly');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (23,2.3,'Hour no find it park');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (24,3.5,'Eat welcomed any');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (25,3.7,'husbands moderate');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (26,4.4,'Led was misery played');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (27,5.1,'waited almost cousin living');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (28,1.7,'Of intention contained');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (29,1.6,'is by middleton am');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (30,1.8,'Principles fat stimulated');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (31,2.9,'uncommonly considered');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (32,3.5,'set especially prosperous');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (33,2.8,'Sons at park');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (34,1.8,'mr meet as fact like. ');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (35,1.4,'Unpacked now declared');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (36,5.8,'put you confined');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (37,4.9,'daughter improved');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (38,3.7,'Celebrated imprudence');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (39,1.5,'few interested');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (40,3.6,'especially reasonable');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (41,4.4,'Wonder bed elinor');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (42,5.3,'It want gave west ');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (43,3.1,'into high no in');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (44,5.8,'Bringing so sociable ');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (45,4.8,'felicity supplied mr');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (46,5.4,'September suspicion');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (47,3.9,'far him two acuteness perfectly');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (48,2.3,'Covered as an examine');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (49,4.3,'Ye astonished friendship');
INSERT INTO inno.paper_brightness (`id`,`Lvl`,`describe`) VALUES (50,4.9,'remarkably no');
