/*
-- Query: SELECT * FROM inno.order_services
-- Date: 2020-11-20 01:20
*/
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (35,2);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (41,2);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (46,7);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (25,8);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (47,8);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (25,9);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (6,12);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (46,14);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (47,14);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (47,16);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (9,17);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (6,18);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (6,19);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (16,20);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (21,20);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (40,21);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (43,21);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (28,22);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (41,22);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (7,23);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (39,25);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (28,26);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (45,27);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (5,31);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (49,35);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (15,36);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (31,36);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (44,38);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (3,39);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (23,40);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (46,40);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (24,41);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (42,41);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (30,43);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (43,43);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (20,44);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (32,44);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (25,45);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (39,45);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (49,46);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (47,48);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (1,49);
INSERT INTO inno.order_services (`fk_order_id`,`fk_service_id`) VALUES (5,50);
